name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip python3-setuptools \
          python3-wheel python3-jinja2 python3-openssl python3-pillow python3-pygments \
          python3-docutils python3-dev build-essential libffi-dev ccache libtool \
          libssl-dev automake autoconf libsqlite3-dev zlib1g-dev libjpeg-dev
        pip install --user buildozer cython

    - name: Build the APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android update
        yes | sdkmanager --licenses
        yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;30.0.3" "ndk;23.1.7779620"
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@main
      with:
        name: okey101-apk
        path: bin/*.apk
